"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, List, Optional, Tuple

def validate(ir: Any, schema: Dict[str, Any], mapping: Optional[List[Tuple[str, Tuple[int, int]]]] = ..., path: str = ...) -> List[Dict[str, Any]]:
    """Validate a Python IR against a minimal JSON-schema-like spec.

    Supported schema keys: 'type' (object, array, string, number, boolean),
    'properties' (dict), 'required' (list), 'items' (schema).

    Returns list of diagnostics: {path, message, node_pos}
    """
    ...

__all__ = ["validate"]
