"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, List, Tuple
from .typed_ast import Block

class RenderResult:
    def __init__(self, ir: Any, mapping: List[Tuple[str, Tuple[int, int]]]) -> None:
        ...
    


def evaluate_ast(root: Block, context: Dict[str, Any], includes: Dict[str, Block] | None = ...) -> RenderResult:
    """Evaluate AST to a target-neutral IR and collect a trivial mapping of node types to positions.

    Mapping is a list of (node_type, start) tuples for nodes that expose `start`.
    """
    ...

def json_serialize(ir: Any) -> str:
    ...

def markdown_serialize(ir: Any) -> str:
    ...

__all__ = ["evaluate_ast", "RenderResult", "json_serialize", "markdown_serialize"]
