"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from typing import Any, Dict, Optional
from temple.typed_ast import Node as ASTNode
from temple.diagnostics import SourceRange
from temple.compiler.types import BaseType

"""
temple.compiler.serializers.base
Abstract serializer interface for multi-format output.

Serializers convert type-checked AST + input data into formatted output
(JSON, Markdown, HTML, YAML, etc.), respecting type annotations and producing valid output.
"""
class SerializationError(Exception):
    """Error during serialization process."""
    def __init__(self, message: str, source_range: Optional[SourceRange] = ...) -> None:
        ...
    


class SerializationContext:
    """Context for tracking serialization state and scope."""
    def __init__(self, data: Dict[str, Any], schema: Optional[BaseType] = ...) -> None:
        """
        Initialize serialization context.

        Args:
            data: Input data to serialize against (variables)
            schema: Optional type schema for validation during serialization
        """
        ...
    
    def get_variable(self, path: str | None) -> Any:
        """
        Get variable value by dot-notation path (e.g., 'user.name').

        Args:
            path: Dot-notation variable path
            None to get current scope
        Returns:
            Value if found, None otherwise

        Raises:
            SerializationError: If path is invalid
        """
        ...
    
    def push_scope(self, data: Any) -> None:
        """Push new scope onto stack."""
        ...
    
    def pop_scope(self) -> None:
        """Pop scope from stack."""
        ...
    
    @property
    def current_scope(self) -> Any:
        """Get current scope data."""
        ...
    


class Serializer(ABC):
    """Abstract base class for format-specific serializers."""
    def __init__(self, pretty: bool = ..., strict: bool = ...) -> None:
        """
        Initialize serializer.

        Args:
            pretty: Enable pretty-printing/formatting
            strict: Enforce strict format validation
        """
        ...
    
    @abstractmethod
    def serialize(self, ast: ASTNode, data: Dict[str, Any]) -> str:
        """
        Serialize AST with input data into formatted output.

        Args:
            ast: Type-checked AST to serialize
            data: Input data (variables) for template

        Returns:
            Formatted output string

        Raises:
            SerializationError: If serialization fails
        """
        ...
    
    @abstractmethod
    def evaluate(self, node: ASTNode, context: SerializationContext) -> Any:
        """
        Recursively evaluate AST node to produce intermediate representation.

        Args:
            node: AST node to evaluate
            context: Serialization context with current scope

        Returns:
            Evaluated value (format-specific)

        Raises:
            SerializationError: If evaluation fails
        """
        ...
    
    @abstractmethod
    def format_value(self, value: Any) -> str:
        """
        Format evaluated value into string for output format.

        Args:
            value: Evaluated value (may be Python type or intermediate representation)

        Returns:
            Formatted string for output
        """
        ...
    


