"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Optional, Set
from temple.compiler.serializers.base import ASTNode, SerializationContext, Serializer

"""
temple.compiler.serializers.html_serializer
HTML output serializer for typed DSL.

Produces valid HTML with proper handling of:
- Tag generation and nesting
- Attribute escaping
- Special characters (entities)
- Void elements (br, hr, img, etc.)
- JavaScript/CSS content sanitization
"""
class HTMLSerializer(Serializer):
    """Serializer for HTML output format."""
    VOID_ELEMENTS: Set[str] = ...
    def __init__(self, pretty: bool = ..., strict: bool = ..., sanitize: bool = ...) -> None:
        """
        Initialize HTML serializer.

        Args:
            pretty: Enable pretty-printing with indentation
            strict: Enforce strict HTML5 validation
            sanitize: Remove potentially unsafe HTML (scripts, event handlers)
        """
        ...
    
    def serialize(self, ast: ASTNode, data: Dict[str, Any]) -> str:
        """
        Serialize AST with input data to HTML string.

        Args:
            ast: Type-checked AST to serialize
            data: Input data (variables)

        Returns:
            Valid HTML string

        Raises:
            SerializationError: If serialization fails
        """
        ...
    
    def evaluate(self, node: ASTNode, context: SerializationContext) -> Any:
        """
        Evaluate AST node to HTML string.

        Args:
            node: AST node
            context: Serialization context

        Returns:
            HTML string representation

        Raises:
            SerializationError: If evaluation fails
        """
        ...
    
    def format_value(self, value: Any) -> str:
        """Format value as HTML-safe string."""
        ...
    
    def tag(self, name: str, content: str = ..., attributes: Optional[Dict[str, str]] = ..., self_closing: bool = ...) -> str:
        """
        Generate HTML tag.

        Args:
            name: Tag name (e.g., 'div', 'span')
            content: Tag content (inner HTML)
            attributes: Dictionary of attributes (auto-escaped)
            self_closing: Generate as self-closing tag

        Returns:
            HTML tag string
        """
        ...
    


