"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict
from temple.compiler.serializers.base import ASTNode, SerializationContext, Serializer

"""
temple.compiler.serializers.json_serializer
JSON output serializer for typed DSL.

Produces valid JSON respecting schema types, with proper handling of:
- Numbers (int vs float)
- Strings (escaping, unicode)
- Arrays and objects
- Null values
"""
class JSONSerializer(Serializer):
    """Serializer for JSON output format."""
    def serialize(self, ast: ASTNode, data: Dict[str, Any]) -> str:
        """
        Serialize AST with input data to JSON string.

        Args:
            ast: Type-checked AST to serialize
            data: Input data (variables)

        Returns:
            Valid JSON string

        Raises:
            SerializationError: If output is not valid JSON-serializable
        """
        ...
    
    def evaluate(self, node: ASTNode, context: SerializationContext) -> Any:
        """
        Evaluate AST node to Python value suitable for JSON encoding.

        Args:
            node: AST node to evaluate.
            context: SerializationContext providing variables and helper utilities used during evaluation.

        Returns:
            A Python value (str/int/float/list/dict/None) suitable for JSON encoding.

        Raises:
            SerializationError: If evaluation fails or the node cannot be resolved.
        """
        ...
    
    def format_value(self, value: Any) -> str:
        """Format value as JSON string."""
        ...
    


