"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict
from temple.compiler.serializers.base import ASTNode, SerializationContext, Serializer

"""
temple.compiler.serializers.markdown_serializer
Markdown output serializer for typed DSL.

Produces valid Markdown with proper handling of:
- Heading levels (# ## ### etc.)
- Lists (unordered - bullet, ordered - numbered)
- Inline formatting (bold, italic, code)
- Code blocks with language tags
- Links and images
- Tables (future)
"""
class MarkdownSerializer(Serializer):
    """Serializer for Markdown output format."""
    def __init__(self, pretty: bool = ..., strict: bool = ..., base_heading_level: int = ...) -> None:
        """
        Initialize Markdown serializer.

        Args:
            pretty: Enable pretty-printing (spacing, newlines)
            strict: Enforce strict Markdown validation
            base_heading_level: Starting heading level (1-6)
        """
        ...
    
    def serialize(self, ast: ASTNode, data: Dict[str, Any]) -> str:
        """
        Serialize AST with input data to Markdown string.

        Args:
            ast: Type-checked AST to serialize
            data: Input data (variables)

        Returns:
            Valid Markdown string

        Raises:
            SerializationError: If serialization fails
        """
        ...
    
    def evaluate(self, node: ASTNode, context: SerializationContext) -> Any:
        """
        Evaluate AST node to Markdown string.

        Args:
            node: AST node
            context: Serialization context

        Returns:
            Markdown string representation

        Raises:
            SerializationError: If evaluation fails
        """
        ...
    
    def format_value(self, value: Any) -> str:
        """Format value as Markdown."""
        ...
    


