"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict
from temple.compiler.serializers.base import ASTNode, SerializationContext, Serializer

"""
temple.compiler.serializers.yaml_serializer
YAML output serializer for typed DSL.

Produces valid YAML with proper handling of:
- Block scalars (|, >)
- Flow styles ({}, [])
- Multi-line strings
- Special scalars (true, false, null, numbers)
- Anchors and references
"""
class YAMLSerializer(Serializer):
    """Serializer for YAML output format."""
    def __init__(self, pretty: bool = ..., strict: bool = ..., flow_style: bool = ...) -> None:
        """
        Initialize YAML serializer.

        Args:
            pretty: Enable pretty-printing (indentation, flow style)
            strict: Enforce strict YAML validation
            flow_style: Use flow style ({}, []) instead of block style
        """
        ...
    
    def serialize(self, ast: ASTNode, data: Dict[str, Any]) -> str:
        """
        Serialize AST with input data to YAML string.

        Args:
            ast: Type-checked AST to serialize
            data: Input data (variables)

        Returns:
            Valid YAML string

        Raises:
            SerializationError: If serialization fails
        """
        ...
    
    def evaluate(self, node: ASTNode, context: SerializationContext) -> Any:
        """
        Evaluate AST node to Python value suitable for YAML encoding.

        Args:
            node: AST node
            context: Serialization context

        Returns:
            Value for YAML encoding (dict, list, str, etc.)

        Raises:
            SerializationError: If evaluation fails
        """
        ...
    
    def format_value(self, value: Any) -> str:
        """Format value as YAML."""
        ...
    


