"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Protocol

"""
Base format linting integration for templated files.

Implements an extensible registry of format detectors following the Strategy
pattern. Each detector returns a confidence score (0.0-1.0) based on filename
and content heuristics; the registry selects the highest-confidence format.
"""
MIN_CONFIDENCE = ...
VSCODE_PASSTHROUGH = ...
def strip_temple_extension(filename: Optional[str], extensions: List[str] = ...) -> Optional[str]:
    """Strip temple suffix from filename, preserving base extension for VS Code detection.

    Args:
        filename: Original filename (e.g., "config.json.tmpl")
        extensions: List of temple extensions to strip (e.g., [".tmpl", ".template"])
            If None, defaults to [".tmpl", ".template"]

    Returns:
        Filename with temple extension removed, or original if no match

    Examples:
        strip_temple_extension("config.json.tmpl") -> "config.json"
        strip_temple_extension("README.md.template") -> "README.md"
        strip_temple_extension("data.tmpl") -> "data"
        strip_temple_extension("data.tpl", [".tpl", ".tmpl"]) -> "data"
        strip_temple_extension("plain_file") -> "plain_file"
    """
    ...

class FormatDetector(Protocol):
    """Protocol for pluggable format detectors."""
    def matches(self, filename: Optional[str], content: str) -> float:
        """Return confidence score in [0.0, 1.0] for this format."""
        ...
    
    def format_name(self) -> str:
        """Return canonical format name (e.g., "json", "yaml")."""
        ...
    


@dataclass
class RegisteredDetector:
    priority: int
    detector: FormatDetector
    ...


class FormatDetectorRegistry:
    """Registry that resolves file formats via pluggable detectors."""
    def __init__(self) -> None:
        ...
    
    def register(self, detector: FormatDetector, priority: int = ...) -> None:
        ...
    
    def detect(self, filename: Optional[str], content: str) -> str:
        ...
    


class _JsonDetector:
    def format_name(self) -> str:
        ...
    
    def matches(self, filename: Optional[str], content: str) -> float:
        ...
    


class _YamlDetector:
    def format_name(self) -> str:
        ...
    
    def matches(self, filename: Optional[str], content: str) -> float:
        ...
    


class _HtmlDetector:
    def format_name(self) -> str:
        ...
    
    def matches(self, filename: Optional[str], content: str) -> float:
        ...
    


class _TomlDetector:
    def format_name(self) -> str:
        ...
    
    def matches(self, filename: Optional[str], content: str) -> float:
        ...
    


class _XmlDetector:
    def format_name(self) -> str:
        ...
    
    def matches(self, filename: Optional[str], content: str) -> float:
        ...
    


class _MarkdownDetector:
    def format_name(self) -> str:
        ...
    
    def matches(self, filename: Optional[str], content: str) -> float:
        ...
    


class BaseFormatLinter:
    """Integrates format detection with base format linting."""
    def __init__(self, delimiters: Optional[Dict[str, tuple]] = ...) -> None:
        ...
    
    def detect_base_format(self, filename: Optional[str], text: str) -> str:
        """Detect the base format using registered detectors with confidence scoring."""
        ...
    
    def lint_base_format(self, text: str, filename: Optional[str] = ...) -> List[Dict[str, Any]]:
        """
        Lint the base format of a templated file by stripping template tokens first.
        Returns diagnostics from the base linter (placeholder).
        """
        ...
    


