"""
This type stub file was generated by pyright.
"""

from typing import Optional
from temple.diagnostics import Diagnostic, SourceRange
from lsprotocol.types import Diagnostic as LspDiagnostic, Range

"""
diagnostic_converter.py
Convert temple core diagnostics to LSP format.
"""
def temple_to_lsp_diagnostic(diag: Diagnostic) -> LspDiagnostic:
    """
    Convert temple Diagnostic to LSP Diagnostic.

    Args:
        diag: Temple core Diagnostic object

    Returns:
        LSP Diagnostic for editor display

    Example:
        >>> from temple.diagnostics import Diagnostic, DiagnosticSeverity, SourceRange, Position as TemplePosition
        >>> temple_diag = Diagnostic(
        ...     message="Unclosed block",
        ...     severity=DiagnosticSeverity.ERROR,
        ...     source_range=SourceRange(TemplePosition(0, 0), TemplePosition(0, 10)),
        ...     code="UNCLOSED_BLOCK"
        ... )
        >>> lsp_diag = temple_to_lsp_diagnostic(temple_diag)
        >>> lsp_diag.severity == LspSeverity.Error
        True
    """
    ...

def source_range_to_lsp_range(source_range: Optional[SourceRange]) -> Range:
    """
    Convert temple SourceRange to LSP Range.

    Args:
        source_range: Temple SourceRange or None

    Returns:
        LSP Range (defaults to 0,0 if source_range is None)
    """
    ...

