"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, List, Optional
from temple.diagnostics import Diagnostic, DiagnosticCollector

"""
linter.py
Core linting logic for templated files.

Integrates temple core parser for comprehensive syntax validation.
"""
class TemplateLinter:
    """
    Template linter with syntax validation using temple core parser.

    Validates template syntax and returns diagnostics for:
    - Unclosed blocks (if, for, etc.)
    - Malformed expressions
    - Invalid statements
    - Syntax errors
    """
    def __init__(self, config: Optional[Dict[str, Any]] = ...) -> None:
        ...
    
    def lint(self, text: str, node_collector: Optional[DiagnosticCollector] = ...) -> List[Diagnostic]:
        """
        Parse template and return syntax diagnostics.

        Args:
            text: Template content to validate

        Returns:
            List of Diagnostic objects with syntax errors

        Example:
            >>> linter = TemplateLinter()
            >>> diagnostics = linter.lint("{% if user.active %}{{ user.name }}")
            >>> len(diagnostics) > 0  # Missing {% end %}
            True
        """
        ...
    


if __name__ == "__main__":
    parser = ...
    args = ...
