"""
This type stub file was generated by pyright.
"""

from typing import Dict, Optional, Tuple

"""
template_preprocessing.py
Utility for stripping/replacing template tokens for base format linting.
"""
def strip_template_tokens(text: str, delimiters: Optional[Dict[str, Tuple[str, str]]] = ..., replace_with: str = ...) -> str:
    """Strips or replaces all template tokens from a templated file.

    Preserves the base format structure for linting. Supports configurable delimiters.

    Regex patterns are cached using functools.lru_cache for performance.
    Subsequent calls with the same delimiter configuration reuse compiled patterns,
    providing 10x+ speedup for batch processing.

    Args:
        text: The input templated text.
        delimiters: Optional dict specifying delimiters for 'statement', 'expression', 'comment'.
            Example::

                {
                    'statement': ('{%','%}'),
                    'expression': ('{{','}}'),
                    'comment': ('{#','#}')
                }

        replace_with: String to replace template tokens with (default: '').

    Returns:
        Text with template tokens stripped or replaced.
    """
    ...

if __name__ == "__main__":
    parser = ...
    args = ...
