# Composite Python job for Temple monorepo
# Usage: jobs.<job_id>.uses: ./.github/workflow-templates/python-job.yml

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      working-directory:
        required: false
        type: string
      uv-install:
        required: false
        type: boolean
        default: true
      extras:
        required: false
        type: string
        default: ""
      run-script:
        required: true
        type: string

jobs:
  python-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install uv
        if: ${{ inputs.uv-install }}
        run: pip install uv
      - name: Install dependencies (uv)
        run: |
          cd ${{ inputs.working-directory || '.' }}
          uv pip install .${{ inputs.extras }}
      - name: Run script
        run: ${{ inputs.run-script }}
