# Reusable Python setup workflow for Temple monorepo
# Usage: jobs.<job_id>.uses: ./.github/workflow-templates/python-setup.yml

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      working-directory:
        required: false
        type: string
      uv-install:
        required: false
        type: boolean
        default: true
      extras:
        required: false
        type: string
        default: ""

jobs:
  setup-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install uv
        if: ${{ inputs.uv-install }}
        run: pip install uv
      - name: Install dependencies (uv)
        run: |
          cd ${{ inputs.working-directory || '.' }}
          uv pip install .${{ inputs.extras }}
      - name: Cache uv wheels
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ inputs.python-version }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: ${{ runner.os }}-uv-
