"""
This type stub file was generated by pyright.
"""

from typing import List, Tuple
from temple.typed_ast import Block
from temple.diagnostics import Diagnostic

class TypedTemplateParser:
    """Lightweight wrapper around the Lark-based parser used in tests.

    parse(text) -> (nodes_list, diagnostics_list)
    """
    def parse(self, text: str) -> Tuple[List[Block], List[Diagnostic]]:
        ...
    


__all__ = ["TypedTemplateParser"]
