"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import List, Optional
from temple.diagnostics import SourceRange

"""
temple.compiler.type_errors
Type error definitions and reporting.

Maps type errors to source positions with actionable suggestions.
"""
class TypeErrorKind:
    """Type error categories."""
    TYPE_MISMATCH = ...
    UNDEFINED_VARIABLE = ...
    MISSING_PROPERTY = ...
    INVALID_CONSTRAINT = ...
    SCHEMA_VIOLATION = ...
    CIRCULAR_REFERENCE = ...
    INCOMPATIBLE_TYPES = ...


@dataclass
class TypeError:
    """Represents a type error with source location."""
    kind: str
    message: str
    source_range: SourceRange
    expected_type: Optional[str] = ...
    actual_type: Optional[str] = ...
    suggestion: Optional[str] = ...
    def to_diagnostic(self) -> dict:
        """Convert to LSP diagnostic format."""
        ...
    
    def format_error(self, source_text: Optional[str] = ...) -> str:
        """Format error with source context for CLI output."""
        ...
    


class TypeErrorCollector:
    """Collects type errors during type checking."""
    def __init__(self) -> None:
        ...
    
    def add_error(self, kind: str, message: str, source_range: SourceRange, expected_type: Optional[str] = ..., actual_type: Optional[str] = ..., suggestion: Optional[str] = ...): # -> None:
        """Add a type error."""
        ...
    
    def add_type_mismatch(self, source_range: SourceRange, expected: str, actual: str, context: str = ...): # -> None:
        """Add a type mismatch error."""
        ...
    
    def add_undefined_variable(self, source_range: SourceRange, var_name: str, available_vars: List[str] = ...): # -> None:
        """Add an undefined variable error."""
        ...
    
    def add_missing_property(self, source_range: SourceRange, property_name: str, object_type: str, available_properties: List[str] = ...): # -> None:
        """Add a missing property error."""
        ...
    
    def add_schema_violation(self, source_range: SourceRange, schema_error: str): # -> None:
        """Add a schema violation error."""
        ...
    
    def has_errors(self) -> bool:
        """Check if any errors were collected."""
        ...
    
    def format_all(self, source_text: Optional[str] = ...) -> str:
        """Format all errors as a single string."""
        ...
    
    def to_diagnostics(self) -> List[dict]:
        """Convert all errors to LSP diagnostic format."""
        ...
    


