"""
This type stub file was generated by pyright.
"""

from temple.typed_ast import Block, Expression, For, If, Include, Text
from temple.diagnostics import Position, SourceRange
from temple.lark_parser import parse_template, parse_with_diagnostics
from temple.compiler.types import AnyType, ArrayType, BaseType, BooleanType, NullType, NumberType, ObjectType, ReferenceType, StringType, TupleType, UnionType, infer_type_from_value, optional
from temple.compiler.schema import Schema, SchemaBuilder, SchemaParser, array_schema, object_schema
from temple.compiler.type_checker import TypeChecker, TypeEnvironment
from temple.compiler.type_errors import TypeError, TypeErrorCollector

"""
temple.compiler
Production-grade typed DSL compiler for Temple.

This package implements:
1. Parser (via lark_parser) — item 34 ✅
2. Type system (types, schema, type_checker) — item 35 ✅
3. Diagnostics (via temple.diagnostics, source_map, error_formatter) — item 36 ✅
4. Serializers (serializers/) — item 37 ✅
"""
__all__ = ["Position", "SourceRange", "Text", "Expression", "If", "For", "Include", "Block", "parse_template", "parse_with_diagnostics", "BaseType", "StringType", "NumberType", "BooleanType", "NullType", "ArrayType", "ObjectType", "TupleType", "UnionType", "ReferenceType", "AnyType", "optional", "infer_type_from_value", "Schema", "SchemaParser", "SchemaBuilder", "object_schema", "array_schema", "TypeChecker", "TypeEnvironment", "TypeError", "TypeErrorCollector"]
