"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Any, Dict, List, Optional
from .types import BaseType

"""
temple.compiler.schema
Schema definitions and validation.

Supports JSON Schema subset and custom schema DSL.
"""
@dataclass
class Schema:
    """Schema definition for a template output."""
    root_type: BaseType
    definitions: Dict[str, BaseType] = ...
    metadata: Dict[str, Any] = ...
    def validate(self, value: Any) -> tuple[bool, Optional[str]]:
        """Validate a value against this schema."""
        ...
    
    def to_json_schema(self) -> Dict[str, Any]:
        """Convert schema to JSON Schema representation."""
        ...
    
    def to_json(self) -> str:
        """Convert schema to JSON string."""
        ...
    


class SchemaParser:
    """Parser for schema definitions."""
    @staticmethod
    def from_json_schema(schema_dict: Dict[str, Any]) -> Schema:
        """Parse a JSON Schema into internal schema representation."""
        ...
    
    @staticmethod
    def from_template_comment(comment_text: str) -> Optional[Schema]:
        """Parse schema from template comment block.

        Expected format:
        {# @schema
        {
          "type": "object",
          "properties": {...}
        }
        #}
        """
        ...
    
    @staticmethod
    def from_file(file_path: str) -> Schema:
        """Load schema from a .schema or .json file."""
        ...
    


class SchemaBuilder:
    """Builder for constructing schemas programmatically."""
    def __init__(self) -> None:
        ...
    
    def add_definition(self, name: str, type_: BaseType) -> SchemaBuilder:
        """Add a named type definition."""
        ...
    
    def build(self, root_type: BaseType, **metadata) -> Schema:
        """Build the schema with the given root type."""
        ...
    


def object_schema(properties: Dict[str, BaseType], required: List[str] = ...) -> Schema:
    """Create a simple object schema."""
    ...

def array_schema(item_type: BaseType) -> Schema:
    """Create a simple array schema."""
    ...

