"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Tuple
from temple.diagnostics import Position, SourceRange

"""
temple.compiler.source_map
Source position tracking and error mapping.

Maps between original template positions, preprocessed positions,
and AST node positions for accurate error reporting.
"""
@dataclass
class PositionMapping:
    """Maps a position in preprocessed text to original text."""
    original_pos: Position
    preprocessed_pos: Position
    ...


class SourceMap:
    """Maps positions between original and preprocessed versions of source."""
    def __init__(self, original_text: str, preprocessed_text: str) -> None:
        """Initialize source map from original and preprocessed text.

        Args:
            original_text: Original template text
            preprocessed_text: Text with DSL tokens removed
        """
        ...
    
    def preprocessed_to_original(self, prep_pos: Position) -> Position:
        """Map position in preprocessed text to original text.

        Args:
            prep_pos: Position in preprocessed text

        Returns:
            Corresponding position in original text
        """
        ...
    
    def original_to_preprocessed(self, orig_pos: Position) -> Position:
        """Map position in original text to preprocessed text.

        Args:
            orig_pos: Position in original text

        Returns:
            Corresponding position in preprocessed text
        """
        ...
    
    def preprocessed_range_to_original(self, prep_range: SourceRange) -> SourceRange:
        """Map a range in preprocessed text to original text.

        Args:
            prep_range: Range in preprocessed text

        Returns:
            Corresponding range in original text
        """
        ...
    
    def original_range_to_preprocessed(self, orig_range: SourceRange) -> SourceRange:
        """Map a range in original text to preprocessed text.

        Args:
            orig_range: Range in original text

        Returns:
            Corresponding range in preprocessed text
        """
        ...
    


class DiagnosticMapper:
    """Maps diagnostics between preprocessed and original text."""
    def __init__(self, source_map: SourceMap) -> None:
        """Initialize mapper with source map.

        Args:
            source_map: SourceMap for position mapping
        """
        ...
    
    def map_from_preprocessed(self, diag_position: Position) -> Position:
        """Map diagnostic position from preprocessed back to original.

        Args:
            diag_position: Position in preprocessed text

        Returns:
            Position in original text
        """
        ...
    
    def map_range_from_preprocessed(self, diag_range: SourceRange) -> SourceRange:
        """Map diagnostic range from preprocessed back to original.

        Args:
            diag_range: Range in preprocessed text

        Returns:
            Range in original text
        """
        ...
    


class PositionTracker:
    """Tracks current position while walking source text."""
    def __init__(self) -> None:
        ...
    
    def advance(self, char: str) -> Position:
        """Advance position by one character.

        Args:
            char: Character being consumed

        Returns:
            Position before advancing
        """
        ...
    
    def advance_string(self, text: str) -> Position:
        """Advance position by multiple characters.

        Args:
            text: Text being consumed

        Returns:
            Position before advancing
        """
        ...
    
    def checkpoint(self) -> Tuple[int, int, int]:
        """Get current position as checkpoint tuple."""
        ...
    
    def restore(self, checkpoint: Tuple[int, int, int]): # -> None:
        """Restore position from checkpoint.

        Args:
            checkpoint: Tuple from checkpoint()
        """
        ...
    


