"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Optional
from temple.typed_ast import Node as ASTNode
from .types import BaseType
from .schema import Schema

"""
temple.compiler.type_checker
Type checking and semantic analysis for typed templates.

Walks AST, assigns types, validates against schema.
"""
class TypeEnvironment:
    """Manages variable bindings and types during type checking."""
    def __init__(self, parent: Optional[TypeEnvironment] = ...) -> None:
        ...
    
    def bind(self, name: str, type_: BaseType): # -> None:
        """Bind a variable name to a type in this scope."""
        ...
    
    def lookup(self, name: str) -> Optional[BaseType]:
        """Look up a variable's type, checking parent scopes."""
        ...
    
    def get_all_names(self) -> List[str]:
        """Get all variable names in scope."""
        ...
    
    def child_scope(self) -> TypeEnvironment:
        """Create a child scope."""
        ...
    


class TypeChecker:
    """Type checker for templates."""
    def __init__(self, schema: Optional[Schema] = ..., data: Optional[Any] = ...) -> None:
        ...
    
    def check(self, ast: ASTNode) -> bool:
        """
        Type check an AST node.

        Returns:
            True if no errors, False if errors were found.
        """
        ...
    
    def validate_output_schema(self, ast: ASTNode) -> bool:
        """
        Validate that the template output will match the schema.

        This is a simplified check - full implementation would
        simulate rendering to determine output structure.
        """
        ...
    


