"""
This type stub file was generated by pyright.
"""

import logging
from typing import List, Optional
from pygls.lsp.client import LanguageClient
from lsprotocol.types import Diagnostic

"""
BaseLintingService - Delegates linting to VS Code's native linters
"""
class BaseLintingService:
    """
    Service responsible for delegating base format linting to VS Code extension.

    This service:
    - Sends cleaned content to VS Code extension
    - Receives diagnostics from native linters (JSON, YAML, etc.)
    - Handles communication errors gracefully
    """
    def __init__(self, logger: logging.Logger = ...) -> None:
        ...
    
    def request_base_diagnostics(self, lc: LanguageClient, cleaned_text: str, original_uri: str, detected_format: Optional[str] = ..., original_filename: Optional[str] = ..., temple_extensions: List[str] = ...) -> List[Diagnostic]:
        """
        Request base format diagnostics from VS Code extension.

        Args:
            lc: Language client for communication
            cleaned_text: Template content with DSL tokens stripped
            original_uri: URI of the original document
            detected_format: Format detected by registry (or VSCODE_PASSTHROUGH)
            original_filename: Original filename for extension stripping
            temple_extensions: List of temple file extensions (e.g., [".tmpl", ".template"])

        Returns:
            List of diagnostics from base format linters
        """
        ...
    


