"""
This type stub file was generated by pyright.
"""

import logging
from typing import List
from lsprotocol.types import Diagnostic
from temple.template_tokenizer import Token

"""
DiagnosticMappingService - Maps diagnostics from cleaned content to original positions
"""
class DiagnosticMappingService:
    """
    Service responsible for mapping diagnostics between cleaned and original content.

    This service:
    - Maps diagnostic positions from cleaned content back to original template
    - Accounts for stripped DSL tokens in position calculations
    - Handles edge cases and errors gracefully
    """
    def __init__(self, logger: logging.Logger = ...) -> None:
        ...
    
    def map_diagnostics(self, diagnostics: List[Diagnostic], text_tokens: List[Token]) -> List[Diagnostic]:
        """
        Map diagnostics from cleaned content to original template positions.

        Args:
            diagnostics: Diagnostics with positions in cleaned content
            text_tokens: Text tokens tracking original positions

        Returns:
            Diagnostics with positions mapped to original template
        """
        ...
    


