"""
This type stub file was generated by pyright.
"""

import logging
from typing import List
from pygls.lsp.client import LanguageClient
from lsprotocol.types import Diagnostic

"""
LintOrchestrator - Coordinates all linting services
"""
class LintOrchestrator:
    """
    Orchestrates the complete linting workflow for templated files.

    Workflow:
    1. Template linting (syntax and logic validation)
    2. Token cleaning (strip DSL tokens)
    3. Base linting (delegate to native linters)
    4. Diagnostic mapping (map positions back to original)
    5. Merge all diagnostics

    This orchestrator coordinates services following Single Responsibility Principle:
    - TemplateLinter: Validates template syntax
    - TokenCleaningService: Strips DSL tokens
    - BaseLintingService: Delegates to native linters
    - DiagnosticMappingService: Maps positions
    """
    def __init__(self, logger: logging.Logger | None = ...) -> None:
        ...
    
    def lint_template(self, text: str, uri: str, language_client: LanguageClient, temple_extensions: List[str] | None = ...) -> List[Diagnostic]:
        """
        Execute complete linting workflow for a templated file.

        Args:
            text: Template content
            uri: Document URI
            language_client: LSP client for base linting delegation
            temple_extensions: List of temple file extensions (e.g., [".tmpl", ".template"])

        Returns:
            Combined list of template and base format diagnostics
        """
        ...
    


