"""
This type stub file was generated by pyright.
"""

from lark import Lark
from typing import List, Literal, Optional, Tuple, overload
from .typed_ast import Block
from .diagnostics import Diagnostic, DiagnosticCollector


def get_parser() -> Lark:
    ...

@overload
def parse_template(text: str, *, include_raw: Literal[False] = ..., node_collector: Optional[DiagnosticCollector] = ...) -> Block:
    """Parse template text and return AST.

    Args:
        text: Template source text
        include_raw: If False (default), return Block AST
        node_collector: Optional collector for diagnostics

    Returns:
        Parsed Block AST

    Raises:
        UnexpectedInput: On syntax errors (use parse_with_diagnostics for error collection)
    """
    ...

@overload
def parse_template(text: str, *, include_raw: Literal[True], node_collector: Optional[DiagnosticCollector] = ...) -> Tuple[Block, object]:
    """Parse template text and return AST with raw parse tree.

    Args:
        text: Template source text
        include_raw: If True, return tuple of (AST, raw Lark tree)
        node_collector: Optional collector for diagnostics

    Returns:
        Tuple of (parsed Block AST, raw Lark tree)

    Raises:
        UnexpectedInput: On syntax errors
    """
    ...

def parse_with_diagnostics(text: str, node_collector: Optional[DiagnosticCollector] = ...) -> Tuple[Block, List[Diagnostic]]:
    """Parse template text and collect diagnostics.

    Args:
        text: Template source text
        node_collector: Optional collector for diagnostics

    Returns:
        Tuple of (AST, diagnostics list). AST may be partial if errors occurred.

    Example:
        >>> ast, diagnostics = parse_with_diagnostics("{% if x %}{{ user.name }}")
        >>> len(diagnostics) > 0  # Missing {% end %}
        True
    """
    ...

__all__ = ["parse_template", "parse_with_diagnostics", "get_parser", "Block", "Diagnostic"]
