"""
This type stub file was generated by pyright.
"""

from typing import Optional, Protocol, TYPE_CHECKING, Tuple
from .diagnostics import Position, SourceRange

if TYPE_CHECKING:
    ...
class RangeLike(Protocol):
    start: Position
    end: Position
    ...


def make_source_range(source_range: Optional[object] = ..., start: Optional[Tuple[int, int]] = ..., end: Optional[Tuple[int, int]] = ..., allow_duck: bool = ...) -> SourceRange:
    """Normalize various range-like inputs into a canonical SourceRange.

    Accepts either a SourceRange, a (start,) or (start,end) tuple pair, or
    a duck-typed object with `.start`/`.end` Position-like attributes when
    `allow_duck` is True.

    Raises:
        TypeError or ValueError on invalid inputs.
    """
    ...

