"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, List, Optional, Tuple
from temple.diagnostics import SourceRange

class TemplateError(Exception): ...

class Node:
    def __init__(self, source_range: SourceRange) -> None: ...
    def evaluate(
        self,
        context: Dict[str, Any],
        includes: Optional[Dict[str, Block]] = ...,
        path: str = ...,
        mapping: Optional[List[Tuple[str, Any]]] = ...,
    ) -> Any: ...

class Text(Node):
    def __init__(self, source_range: SourceRange, text: str) -> None: ...
    def evaluate(
        self,
        context: Dict[str, Any],
        includes: Optional[Dict[str, Block]] = ...,
        path: str = ...,
        mapping: Optional[List[Tuple[str, Any]]] = ...,
    ) -> str: ...

class Expression(Node):
    def __init__(self, source_range: SourceRange, expr: str) -> None: ...
    def evaluate(
        self,
        context: Dict[str, Any],
        includes: Optional[Dict[str, Block]] = ...,
        path: str = ...,
        mapping: Optional[List[Tuple[str, Any]]] = ...,
    ) -> Any: ...

class If(Node):
    def __init__(
        self,
        source_range: SourceRange,
        condition: str,
        body: Block,
        else_if_parts: Optional[List[Tuple[str, Block]]] = ...,
        else_body: Optional[Block] = ...,
    ) -> None: ...
    def evaluate(
        self,
        context: Dict[str, Any],
        includes: Optional[Dict[str, Block]] = ...,
        path: str = ...,
        mapping: Optional[List[Tuple[str, Any]]] = ...,
    ) -> Any: ...

class For(Node):
    def __init__(
        self, source_range: SourceRange, var: str, iterable: str, body: Block
    ) -> None: ...
    def evaluate(
        self,
        context: Dict[str, Any],
        includes: Optional[Dict[str, Block]] = ...,
        path: str = ...,
        mapping: Optional[List[Tuple[str, Any]]] = ...,
    ) -> List[Any]: ...

class Include(Node):
    def __init__(self, source_range: SourceRange, name: str) -> None: ...
    def evaluate(
        self,
        context: Dict[str, Any],
        includes: Optional[Dict[str, Block]] = ...,
        path: str = ...,
        mapping: Optional[List[Tuple[str, Any]]] = ...,
    ) -> Any: ...

class Block(Node):
    def __init__(self, source_range: SourceRange, nodes: List[Node]) -> None:
        """Create a block with given nodes.

        Args:
            source_range: Source position range
            nodes: List of child nodes
        """
        ...

    def __iter__(self):  # -> Iterator[Any]:
        ...
    def __len__(self):  # -> int:
        ...
    def __getitem__(self, idx): ...
    def evaluate(
        self,
        context: Dict[str, Any],
        includes: Optional[Dict[str, Block]] = ...,
        path: str = ...,
        mapping: Optional[List[Tuple[str, Any]]] = ...,
    ) -> Any: ...

class Array(Node):
    def __init__(self, source_range: SourceRange, items: List[Node]) -> None: ...
    def evaluate(
        self,
        context: Dict[str, Any],
        includes: Optional[Dict[str, Block]] = ...,
        path: str = ...,
        mapping: Optional[List[Tuple[str, Any]]] = ...,
    ) -> List[Any]: ...

class ObjectNode(Node):
    def __init__(
        self,
        pairs: Optional[List[Tuple[str, Node]]] = ...,
        start: Optional[Tuple[int, int]] = ...,
    ) -> None: ...
    def evaluate(
        self,
        context: Dict[str, Any],
        includes: Optional[Dict[str, Block]] = ...,
        path: str = ...,
        mapping: Optional[List[Tuple[str, Tuple[int, int]]]] = ...,
    ) -> Dict[str, Any]: ...

class FunctionDef(Node): ...
class FunctionCall(Node): ...

__all__ = [
    "Node",
    "Text",
    "Expression",
    "If",
    "For",
    "Include",
    "Block",
    "Array",
    "ObjectNode",
    "TemplateError",
    "FunctionDef",
    "FunctionCall",
]
