"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, List, Optional, Tuple
from temple.diagnostics import Position, SourceRange

class TemplateError(Exception):
    ...


class Node:
    def __init__(self, source_range: SourceRange) -> None:
        ...
    
    @property
    def source_range(self) -> SourceRange:
        ...
    
    def evaluate(self, context: Dict[str, Any], includes: Optional[Dict[str, Block]] = ..., path: str = ..., mapping: Optional[List[Tuple[str, Position]]] = ...) -> Any:
        ...
    


class Text(Node):
    def __init__(self, source_range: SourceRange, text: str) -> None:
        ...
    
    def evaluate(self, context: Dict[str, Any], includes: Optional[Dict[str, Block]] = ..., path: str = ..., mapping: Optional[List[Tuple[str, Position]]] = ...) -> str:
        ...
    


class Expression(Node):
    def __init__(self, source_range: SourceRange, expr: Optional[str] = ...) -> None:
        ...
    
    def evaluate(self, context: Dict[str, Any], includes: Optional[Dict[str, Block]] = ..., path: str = ..., mapping: Optional[List[Tuple[str, Position]]] = ...) -> Any:
        ...
    


class If(Node):
    def __init__(self, source_range: SourceRange, condition: str, body: Block, else_if_parts: Optional[List[Tuple[str, Block]]] = ..., else_body: Optional[Block] = ...) -> None:
        ...
    
    def evaluate(self, context: Dict[str, Any], includes: Optional[Dict[str, Block]] = ..., path: str = ..., mapping: Optional[List[Tuple[str, Position]]] = ...) -> Any:
        ...
    


class For(Node):
    def __init__(self, source_range: SourceRange, var: str, iterable: str, body: Block) -> None:
        ...
    
    def evaluate(self, context: Dict[str, Any], includes: Optional[Dict[str, Block]] = ..., path: str = ..., mapping: Optional[List[Tuple[str, Position]]] = ...) -> List[Any]:
        ...
    


class Include(Node):
    def __init__(self, source_range: SourceRange, name: str) -> None:
        ...
    
    def evaluate(self, context: Dict[str, Any], includes: Optional[Dict[str, Block]] = ..., path: str = ..., mapping: Optional[List[Tuple[str, Position]]] = ...) -> Any:
        ...
    


class Block(Node):
    def __init__(self, nodes: Optional[List[Node]], name: Optional[str] = ...) -> None:
        ...
    
    def __iter__(self): # -> Iterator[Node]:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __getitem__(self, idx: int) -> Node:
        ...
    
    def evaluate(self, context: Dict[str, Any], includes: Optional[Dict[str, Block]] = ..., path: str = ..., mapping: Optional[List[Tuple[str, Position]]] = ...) -> Any:
        ...
    


class Array(Node):
    def __init__(self, source_range: SourceRange, items: Optional[List[Node]] = ...) -> None:
        ...
    
    def evaluate(self, context: Dict[str, Any], includes: Optional[Dict[str, Block]] = ..., path: str = ..., mapping: Optional[List[Tuple[str, Position]]] = ...) -> List[Any]:
        ...
    


class ObjectNode(Node):
    def __init__(self, source_range: SourceRange, pairs: Optional[List[Tuple[str, Node]]] = ...) -> None:
        ...
    
    def evaluate(self, context: Dict[str, Any], includes: Optional[Dict[str, Block]] = ..., path: str = ..., mapping: Optional[List[Tuple[str, Position]]] = ...) -> Dict[str, Any]:
        ...
    


class FunctionDef(Node):
    ...


class FunctionCall(Node):
    ...


__all__ = ["Node", "Text", "Expression", "If", "For", "Include", "Block", "Array", "ObjectNode", "TemplateError", "FunctionDef", "FunctionCall"]
